USE `temperature_log`;

-- Add sensors.
INSERT INTO sensors VALUES(NULL,'Front Bedroom','indoor');
INSERT INTO sensors VALUES(NULL,'Master Bedroom','indoor');
INSERT INTO sensors VALUES(NULL,'Outside','outdoor');

-- Add temps for first sensor.
INSERT INTO temps VALUES(NULL,1,67.85,UNIX_TIMESTAMP(NOW() - INTERVAL 10 HOUR));
INSERT INTO temps VALUES(NULL,1,68.25,UNIX_TIMESTAMP(NOW() - INTERVAL 9 HOUR));
INSERT INTO temps VALUES(NULL,1,68.80,UNIX_TIMESTAMP(NOW() - INTERVAL 8 HOUR));
INSERT INTO temps VALUES(NULL,1,69.50,UNIX_TIMESTAMP(NOW() - INTERVAL 7 HOUR));
INSERT INTO temps VALUES(NULL,1,69.90,UNIX_TIMESTAMP(NOW() - INTERVAL 6 HOUR));
INSERT INTO temps VALUES(NULL,1,70.01,UNIX_TIMESTAMP(NOW() - INTERVAL 5 HOUR));
INSERT INTO temps VALUES(NULL,1,70.90,UNIX_TIMESTAMP(NOW() - INTERVAL 4 HOUR));
INSERT INTO temps VALUES(NULL,1,71.02,UNIX_TIMESTAMP(NOW() - INTERVAL 3 HOUR));
INSERT INTO temps VALUES(NULL,1,71.02,UNIX_TIMESTAMP(NOW() - INTERVAL 2 HOUR));
INSERT INTO temps VALUES(NULL,1,70.95,UNIX_TIMESTAMP(NOW() - INTERVAL 1 HOUR));
INSERT INTO temps VALUES(NULL,1,71.20,UNIX_TIMESTAMP());

-- Add temps for second sensor.
INSERT INTO temps VALUES(NULL,2,70.90,UNIX_TIMESTAMP(NOW() - INTERVAL 10 HOUR));
INSERT INTO temps VALUES(NULL,2,70.01,UNIX_TIMESTAMP(NOW() - INTERVAL 9 HOUR));
INSERT INTO temps VALUES(NULL,2,69.67,UNIX_TIMESTAMP(NOW() - INTERVAL 8 HOUR));
INSERT INTO temps VALUES(NULL,2,69.50,UNIX_TIMESTAMP(NOW() - INTERVAL 7 HOUR));
INSERT INTO temps VALUES(NULL,2,68.90,UNIX_TIMESTAMP(NOW() - INTERVAL 6 HOUR));
INSERT INTO temps VALUES(NULL,2,67.80,UNIX_TIMESTAMP(NOW() - INTERVAL 5 HOUR));
INSERT INTO temps VALUES(NULL,2,67.70,UNIX_TIMESTAMP(NOW() - INTERVAL 4 HOUR));
INSERT INTO temps VALUES(NULL,2,67.65,UNIX_TIMESTAMP(NOW() - INTERVAL 3 HOUR));
INSERT INTO temps VALUES(NULL,2,67.40,UNIX_TIMESTAMP(NOW() - INTERVAL 2 HOUR));
INSERT INTO temps VALUES(NULL,2,67.32,UNIX_TIMESTAMP(NOW() - INTERVAL 1 HOUR));
INSERT INTO temps VALUES(NULL,2,68.20,UNIX_TIMESTAMP());

-- Add temps for third sensor.
INSERT INTO temps VALUES(NULL,3,55.80,UNIX_TIMESTAMP(NOW() - INTERVAL 10 HOUR));
INSERT INTO temps VALUES(NULL,3,55.95,UNIX_TIMESTAMP(NOW() - INTERVAL 9 HOUR));
INSERT INTO temps VALUES(NULL,3,57.42,UNIX_TIMESTAMP(NOW() - INTERVAL 8 HOUR));
INSERT INTO temps VALUES(NULL,3,59.10,UNIX_TIMESTAMP(NOW() - INTERVAL 7 HOUR));
INSERT INTO temps VALUES(NULL,3,62.80,UNIX_TIMESTAMP(NOW() - INTERVAL 6 HOUR));
INSERT INTO temps VALUES(NULL,3,62.85,UNIX_TIMESTAMP(NOW() - INTERVAL 5 HOUR));
INSERT INTO temps VALUES(NULL,3,63.00,UNIX_TIMESTAMP(NOW() - INTERVAL 4 HOUR));
INSERT INTO temps VALUES(NULL,3,64.65,UNIX_TIMESTAMP(NOW() - INTERVAL 3 HOUR));
INSERT INTO temps VALUES(NULL,3,63.40,UNIX_TIMESTAMP(NOW() - INTERVAL 2 HOUR));
INSERT INTO temps VALUES(NULL,3,63.32,UNIX_TIMESTAMP(NOW() - INTERVAL 1 HOUR));
INSERT INTO temps VALUES(NULL,3,62.20,UNIX_TIMESTAMP());
